### ISSUE TITLE
Add support for arm64 linux

### ISSUE THREAD

**Issue by navels** [vovayartsev/wkhtmltopdf-installer-ruby#10]
PR: https://github.com/vovayartsev/wkhtmltopdf-installer-ruby/pull/9

**Comment by navels** [comment]
@vovayartsev are you available?

**Comment by navels** [comment]
@vovayartsev

**Comment by jhuckabee** [comment]
ping @vovayartsev

**Comment by vovayartsev** [comment]
Thank you @navels (and @jhuckabee for the reminder 👍 )
Looking into the PR now

**Comment by vovayartsev** [comment]
Just uploaded the binary to the Releases and merged the PR.
If someone could confirm that the`master` branch works on arm64 linux - I'll release it to Rubygems.

Thanks again for your contribution @navels 🙏

**Comment by navels** [comment]
Thanks!  Seems I was mistaken about the binary, I actually need

https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_arm64.deb

i.e., debian buster, not ubuntu bionic.

**Comment by vovayartsev** [comment]
👌 I've just put a new binary to Releases. Does it work now?

**Comment by jhuckabee** [comment]
I can confirm the installing from master works for me on debian stretch. Thanks for the update @vovayartsev

**Comment by navels** [comment]
Success, thanks!

**Comment by vovayartsev** [comment]
Thanks for confirming!
Released to [Rubygems](https://rubygems.org/gems/wkhtmltopdf-installer/versions/0.12.6.3)
